name: hw-kafka-client
version: '2.4.1'
synopsis: Kafka bindings for Haskell
description: ! 'Apache Kafka bindings backed by the librdkafka C library.


  Features include:


  * Consumer groups: auto-rebalancing consumers


  * Keyed and keyless messages producing/consuming


  * Batch producing messages'
category: Database
author: Alexey Raga <alexey.raga@gmail.com>
maintainer: Alexey Raga <alexey.raga@gmail.com>
license: MIT
homepage: https://github.com/haskell-works/hw-kafka-client
git: git://github.com/haskell-works/hw-kafka-client.git
bug-reports: https://github.com/haskell-works/hw-kafka-client/issues
extra-source-files:
- README.md
dependencies:
- base >=4.6 && <5
- bifunctors
- bytestring
- containers
library:
  source-dirs: src
  ghc-options: -Wall
  extra-libraries: rdkafka
  build-tools:
  - c2hs
  exposed-modules:
  - Kafka.Consumer
  - Kafka.Consumer.ConsumerProperties
  - Kafka.Consumer.Subscription
  - Kafka.Consumer.Types
  - Kafka.Dump
  - Kafka.Metadata
  - Kafka.Producer
  - Kafka.Producer.ProducerProperties
  - Kafka.Producer.Types
  - Kafka.Types
  dependencies:
  - temporary
  - transformers
  - unix
  when:
  - condition: impl(ghc <8.0)
    dependencies:
    - semigroups
  - condition: os(osx)
    cpp-options:
    - -D__attribute__(A)=
    - -D_Nullable=
    - -D_Nonnull=
executables:
  kafka-client-example:
    main: Main.hs
    source-dirs: example
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - temporary
    - transformers
    - unix
    - hw-kafka-client
    when:
    - condition: ! '!(flag(examples))'
      buildable: false
tests:
  tests:
    main: Spec.hs
    source-dirs: tests
    ghc-options:
    - -Wall
    - -threaded
    dependencies:
    - hw-kafka-client
    - monad-loops
    - hspec
    - either
  integration-tests:
    main: Spec.hs
    source-dirs: tests-it
    ghc-options:
    - -Wall
    - -threaded
    dependencies:
    - hw-kafka-client
    - monad-loops
    - hspec
    - either
flags:
  examples:
    description: Also compile examples
    manual: true
    default: false
