flags: {}
packages:
- '.'
extra-deps:

resolver: lts-9.1

docker:
  enable: false
  repo: "fpco/stack-build:latest"
  auto-pull: true
  env:
    - "LD_LIBRARY_PATH=.librdkafka/lib"
    - "LD_INCLUDE_PATH=.librdkafka/include/librdkafka"
