#!/usr/bin/env bash

if [ "$_system_type" == "Darwin" ]; then
  sed () {
    gsed "$@"
  }
fi

if [ "$HACKAGE_USER" == "" ] || [ "$HACKAGE_PASS" == "" ]; then
  echo "Must supply credentials"
  exit 1
fi

_repo_name=$(basename `git rev-parse --show-toplevel`)

_version=$(
  cat $_repo_name.cabal | grep '^version:' | head | cut -d ':' -f 2 | xargs
)

if [ "v$_version" != "$CIRCLE_TAG" ]; then
  echo "Tag mismatch: "v$_version != $CIRCLE_TAG""
  exit 1
fi

cabal configure

cabal sdist

if [ "$ALLOW_UPLOAD" != "" ]; then
  cabal upload \
    --username=$HACKAGE_USER \
    --password=$HACKAGE_PASS \
    "dist/${_repo_name}-${_version}.tar.gz"
fi
